[package]
name = "scop"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = { path = "gl" }
sdl2 = { version = "0.35.2", features = ["bundled", "static-link"]}
image = "0.24.1"
num = "0.4.0"
rand = "0.8.5"
