[package]
name = "scop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
vulkanalia = { version = "0.14.0", features = ["libloading", "window"] }